/**
 * Provider/model capability profiles — facts derived from official notes + adapter reality.
 * Unverified marketing claims are NOT recorded as supported.
 */

import type { MediaCapabilityProfile } from "./types";
import { provenance } from "./provenance";
import { PROVIDER_VIDEO_CAPABILITIES } from "../../runtime/providerCapabilities";

const DOC = (notes?: string) =>
  provenance("provider_documentation", "probable", notes, "2026-09-05T00:00:00.000Z");
const ADAPTER = (notes?: string) =>
  provenance("adapter", "verified", notes, "2026-09-05T00:00:00.000Z");
const MANUAL = (notes?: string) =>
  provenance("manual_verification", "verified", notes, "2026-09-05T00:00:00.000Z");

function baseVideoExecution(adapterSupported: boolean) {
  return {
    mode: "async" as const,
    supportsPolling: true,
    supportsWebhooks: false,
    supportsCancellation: false,
    supportsBatch: false,
    supportsStreaming: false,
    returnsInlineBinary: false,
    returnsTemporaryUrl: true,
    returnsPersistentUrl: false,
    urlExpirationKnown: false,
    requiresDownloadBeforePersistence: true,
    provenance: ADAPTER("Production video adapters return URLs that SPARK must persist"),
  };
}

function emptyAudio() {
  return {
    provenance: DOC("Audio capabilities not asserted unless native audio is known"),
  };
}

function promptCamera() {
  return {
    controlLevel: "prompt_only" as const,
    provenance: DOC("Camera described via prompt only — not structured camera API"),
  };
}

function promptMotion() {
  return {
    controlLevel: "prompt_only" as const,
    supportsMotionStrength: false,
    provenance: DOC("Motion described via prompt only unless otherwise noted"),
  };
}

/**
 * Profiles for providers SPARK actually routes/executes for video, image, and voice.
 * Providers without SPARK adapters are marked adapterSupported:false.
 */
export const MEDIA_CAPABILITY_PROFILES: MediaCapabilityProfile[] = [
  // Kling AI
  {
    providerId: "kling",
    modelId: "kling-v2-6",
    displayName: "Kling 2.6 Pro (image_tail)",
    modalities: ["video", "image"],
    generationModes: ["image_to_video"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image", "character", "face"],
      maxReferences: 1,
      supportsMultipleReferences: false,
      supportsTypedReferences: false,
      provenance: MANUAL("Kling I2V uses start image; identity refs limited in SPARK adapter"),
    },
    temporal: {
      supportsStartFrame: true,
      supportsEndFrame: true,
      supportsStartAndEndFrame: true,
      supportsTailFrame: true,
      supportsPreviousShotFrame: true,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: true,
      provenance: MANUAL("Kling image_tail / end-frame supported via production I2V adapter"),
    },
    camera: promptCamera(),
    motion: promptMotion(),
    output: {
      duration: {
        supportedValues: [...PROVIDER_VIDEO_CAPABILITIES.kling.allowedDurationsSec],
        minSeconds: 5,
        maxSeconds: 10,
      },
      aspectRatios: ["16:9", "9:16", "1:1"],
      supportsNativeAudio: true,
      provenance: DOC(PROVIDER_VIDEO_CAPABILITIES.kling.notes),
    },
    audio: { nativeAudioGeneration: true, provenance: DOC("Native audio optional on Kling modes") },
    execution: baseVideoExecution(true),
    controls: {
      seed: false,
      negativePrompt: false,
      provenance: ADAPTER("Controls limited to what videoI2vAdapter passes today"),
    },
    limits: {
      maxDurationSec: 10,
      maxReferenceCount: 1,
      supportedOutputFormats: ["video/mp4"],
    },
    economics: { known: false, notes: "No authoritative SPARK price table" },
    metadata: {
      aliases: ["kling-2.6"],
      status: "active",
    },
  },
  {
    providerId: "kling",
    modelId: "kling-v1-6",
    displayName: "Kling 1.6 Image2Video",
    modalities: ["video", "image"],
    generationModes: ["image_to_video"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image"],
      maxReferences: 1,
      supportsMultipleReferences: false,
      supportsTypedReferences: false,
      provenance: MANUAL("Kling 1.6 I2V uses start image"),
    },
    temporal: {
      supportsStartFrame: true,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: true,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: MANUAL("Kling 1.6 does not support end frame in adapter"),
    },
    camera: promptCamera(),
    motion: promptMotion(),
    output: {
      duration: {
        supportedValues: [5, 10],
        minSeconds: 5,
        maxSeconds: 10,
      },
      aspectRatios: ["16:9", "9:16", "1:1"],
      supportsNativeAudio: true,
      provenance: DOC(),
    },
    audio: { nativeAudioGeneration: true, provenance: DOC() },
    execution: baseVideoExecution(true),
    controls: { seed: false, negativePrompt: false, provenance: ADAPTER() },
    limits: { maxDurationSec: 10, maxReferenceCount: 1, supportedOutputFormats: ["video/mp4"] },
    economics: { known: false },
    metadata: {
      aliases: ["kling-1.6"],
      status: "active",
    },
  },
  {
    providerId: "kling",
    modelId: "kling-v3-omni",
    displayName: "Kling v3 Omni (R2V preview)",
    modalities: ["video", "image"],
    generationModes: ["image_to_video"],
    adapterSupported: false,
    references: {
      supportedTypes: ["image", "character", "face"],
      maxReferences: 4,
      supportsMultipleReferences: true,
      supportsTypedReferences: true,
      provenance: DOC("R2V identity preview"),
    },
    temporal: {
      supportsStartFrame: true,
      supportsEndFrame: true,
      supportsStartAndEndFrame: true,
      supportsTailFrame: true,
      supportsPreviousShotFrame: true,
      supportsVideoContinuation: true,
      supportsVideoExtension: true,
      supportsPreviousVideoAsInput: true,
      supportsLastFrameContinuation: true,
      provenance: DOC(),
    },
    camera: promptCamera(),
    motion: promptMotion(),
    output: {
      duration: { supportedValues: [5, 10], minSeconds: 5, maxSeconds: 10 },
      aspectRatios: ["16:9", "9:16", "1:1"],
      supportsNativeAudio: true,
      provenance: DOC(),
    },
    audio: { nativeAudioGeneration: true, provenance: DOC() },
    execution: baseVideoExecution(false),
    controls: { provenance: DOC() },
    limits: { maxDurationSec: 10, maxReferenceCount: 4 },
    economics: { known: false },
    metadata: { status: "unknown", notes: "Preview model — SPARK adapter not registered" },
  },

  // Seedance / Ark
  {
    providerId: "seedance",
    modelId: "doubao-seedance-1-5-pro-251215",
    displayName: "Seedance 1.5 Pro",
    modalities: ["video", "image"],
    generationModes: ["image_to_video"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image", "character", "environment", "location", "style"],
      maxReferences: 4,
      supportsMultipleReferences: true,
      supportsTypedReferences: true,
      provenance: MANUAL("Seedance first_frame / last_frame / reference_image roles"),
    },
    temporal: {
      supportsStartFrame: true,
      supportsEndFrame: true,
      supportsStartAndEndFrame: true,
      supportsTailFrame: true,
      supportsPreviousShotFrame: true,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: true,
      provenance: MANUAL("Seedance first+last frame supported in SPARK adapter"),
    },
    camera: promptCamera(),
    motion: promptMotion(),
    output: {
      duration: {
        supportedValues: [...PROVIDER_VIDEO_CAPABILITIES.seedance.allowedDurationsSec],
        minSeconds: 4,
        maxSeconds: 15,
      },
      aspectRatios: ["16:9", "9:16", "1:1"],
      resolutions: ["720p", "1080p"],
      supportsNativeAudio: true,
      provenance: DOC(PROVIDER_VIDEO_CAPABILITIES.seedance.notes),
    },
    audio: { nativeAudioGeneration: true, provenance: DOC() },
    execution: baseVideoExecution(true),
    controls: { provenance: ADAPTER() },
    limits: { maxDurationSec: 15, maxReferenceCount: 4, supportedOutputFormats: ["video/mp4"] },
    economics: { known: false },
    metadata: {
      aliases: ["doubao-seedance-1-5-pro", "seedance-1.5"],
      status: "active",
    },
  },
  {
    providerId: "seedance",
    modelId: "doubao-seedance-2-0-260128",
    displayName: "Seedance 2.0",
    modalities: ["video", "image"],
    generationModes: ["image_to_video"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image"],
      maxReferences: 2,
      supportsMultipleReferences: true,
      supportsTypedReferences: false,
      provenance: DOC("Seedance 2.0 first/last frame, no mixed refs"),
    },
    temporal: {
      supportsStartFrame: true,
      supportsEndFrame: true,
      supportsStartAndEndFrame: true,
      supportsTailFrame: true,
      supportsPreviousShotFrame: true,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: true,
      provenance: DOC(),
    },
    camera: promptCamera(),
    motion: promptMotion(),
    output: {
      duration: {
        supportedValues: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        minSeconds: 4,
        maxSeconds: 15,
      },
      aspectRatios: ["16:9", "9:16", "1:1"],
      resolutions: ["720p", "1080p"],
      supportsNativeAudio: true,
      provenance: DOC(),
    },
    audio: { nativeAudioGeneration: true, provenance: DOC() },
    execution: baseVideoExecution(true),
    controls: { provenance: ADAPTER() },
    limits: { maxDurationSec: 15, maxReferenceCount: 2, supportedOutputFormats: ["video/mp4"] },
    economics: { known: false },
    metadata: {
      aliases: ["doubao-seedance-2-0", "seedance-2.0"],
      status: "active",
    },
  },

  // xAI Grok
  {
    providerId: "grok",
    modelId: "grok-imagine-video-1.5",
    displayName: "Grok Imagine Video 1.5",
    modalities: ["video", "image"],
    generationModes: ["image_to_video"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image", "face", "character"],
      maxReferences: 7,
      supportsMultipleReferences: true,
      supportsTypedReferences: false,
      provenance: DOC("Start-frame + reference faces per provider notes"),
    },
    temporal: {
      supportsStartFrame: true,
      supportsEndFrame: true,
      supportsStartAndEndFrame: true,
      supportsTailFrame: true,
      supportsPreviousShotFrame: true,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: ADAPTER("SPARK Grok adapter: official i2v supports first_frame + last_frame_url"),
    },
    camera: promptCamera(),
    motion: promptMotion(),
    output: {
      duration: {
        supportedValues: [...PROVIDER_VIDEO_CAPABILITIES.grok.allowedDurationsSec],
        minSeconds: 1,
        maxSeconds: 15,
      },
      aspectRatios: ["16:9", "9:16", "1:1"],
      supportsNativeAudio: true,
      provenance: DOC(PROVIDER_VIDEO_CAPABILITIES.grok.notes),
    },
    audio: { nativeAudioGeneration: true, provenance: DOC() },
    execution: baseVideoExecution(true),
    controls: { provenance: ADAPTER() },
    limits: { maxDurationSec: 15, maxReferenceCount: 7, supportedOutputFormats: ["video/mp4"] },
    economics: { known: false },
    metadata: {
      status: "active",
    },
  },
  {
    providerId: "grok",
    modelId: "grok-imagine-image-2.0",
    displayName: "Grok Imagine Image 2.0",
    modalities: ["image", "text"],
    generationModes: ["text_to_image", "image_to_image"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image", "style"],
      maxReferences: 1,
      supportsMultipleReferences: false,
      provenance: DOC(),
    },
    temporal: {
      supportsStartFrame: false,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: false,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: MANUAL("Not a video model"),
    },
    camera: { controlLevel: "none", provenance: DOC() },
    motion: { controlLevel: "none", provenance: DOC() },
    output: {
      aspectRatios: ["1:1", "16:9", "9:16"],
      provenance: DOC(),
    },
    audio: emptyAudio(),
    execution: {
      mode: "sync",
      supportsPolling: false,
      supportsWebhooks: false,
      returnsTemporaryUrl: true,
      requiresDownloadBeforePersistence: true,
      provenance: ADAPTER(),
    },
    controls: { seed: false, provenance: ADAPTER() },
    limits: { maxReferenceCount: 1, supportedOutputFormats: ["image/jpeg", "image/png"] },
    economics: { known: false },
    metadata: {
      aliases: ["grok-imagine-image"],
      status: "active",
    },
  },
  {
    providerId: "grok",
    modelId: "grok-tts-eve",
    displayName: "xAI Grok TTS (Eve Voice)",
    modalities: ["audio", "text"],
    generationModes: ["text_to_speech"],
    adapterSupported: true,
    references: { supportedTypes: [], supportsMultipleReferences: false, provenance: DOC() },
    temporal: {
      supportsStartFrame: false,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: false,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: MANUAL(),
    },
    camera: { controlLevel: "none", provenance: DOC() },
    motion: { controlLevel: "none", provenance: DOC() },
    output: { provenance: DOC() },
    audio: { speech: true, nativeAudioGeneration: true, provenance: DOC("Grok voice synthesis") },
    execution: { mode: "sync", supportsPolling: false, supportsWebhooks: false, returnsTemporaryUrl: true, requiresDownloadBeforePersistence: true, provenance: ADAPTER() },
    controls: { provenance: ADAPTER() },
    limits: { supportedOutputFormats: ["audio/mpeg"] },
    economics: { known: false },
    metadata: { status: "active" },
  },

  // Google Gemini / Veo / Imagen
  {
    providerId: "gemini",
    modelId: "veo-3.1-generate-preview",
    displayName: "Gemini Veo 3.1",
    modalities: ["video", "image", "text"],
    generationModes: ["text_to_video", "image_to_video"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image"],
      maxReferences: 1,
      supportsMultipleReferences: false,
      provenance: DOC(PROVIDER_VIDEO_CAPABILITIES.gemini.notes),
    },
    temporal: {
      supportsStartFrame: true,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: true,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: DOC("Veo start-frame / image-conditioned; end-frame not claimed in SPARK adapter"),
    },
    camera: promptCamera(),
    motion: promptMotion(),
    output: {
      duration: {
        supportedValues: [...PROVIDER_VIDEO_CAPABILITIES.gemini.allowedDurationsSec],
        minSeconds: 4,
        maxSeconds: 8,
      },
      aspectRatios: ["16:9", "9:16"],
      supportsNativeAudio: true,
      provenance: DOC(PROVIDER_VIDEO_CAPABILITIES.gemini.notes),
    },
    audio: { nativeAudioGeneration: true, provenance: DOC() },
    execution: {
      ...baseVideoExecution(true),
      mode: "both",
      provenance: ADAPTER("Veo path via ModelRouter / injectable submitVideo"),
    },
    controls: { provenance: ADAPTER() },
    limits: { maxDurationSec: 8, maxReferenceCount: 1, supportedOutputFormats: ["video/mp4"] },
    economics: { known: false },
    metadata: {
      aliases: ["veo", "veo-3.1"],
      status: "active",
    },
  },
  {
    providerId: "gemini",
    modelId: "veo-2.0-generate-001",
    displayName: "Gemini Veo 2.0",
    modalities: ["video", "image", "text"],
    generationModes: ["text_to_video", "image_to_video"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image"],
      maxReferences: 1,
      supportsMultipleReferences: false,
      provenance: DOC(),
    },
    temporal: {
      supportsStartFrame: true,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: true,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: DOC(),
    },
    camera: promptCamera(),
    motion: promptMotion(),
    output: {
      duration: {
        supportedValues: [4, 6, 8],
        minSeconds: 4,
        maxSeconds: 8,
      },
      aspectRatios: ["16:9", "9:16"],
      supportsNativeAudio: true,
      provenance: DOC(),
    },
    audio: { nativeAudioGeneration: true, provenance: DOC() },
    execution: {
      ...baseVideoExecution(true),
      mode: "both",
      provenance: ADAPTER(),
    },
    controls: { provenance: ADAPTER() },
    limits: { maxDurationSec: 8, maxReferenceCount: 1, supportedOutputFormats: ["video/mp4"] },
    economics: { known: false },
    metadata: {
      aliases: ["veo-2.0"],
      status: "active",
    },
  },
  {
    providerId: "gemini",
    modelId: "imagen-3.0-generate-002",
    displayName: "Google Imagen 3.0",
    modalities: ["image", "text"],
    generationModes: ["text_to_image", "image_to_image"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image"],
      maxReferences: 1,
      supportsMultipleReferences: false,
      provenance: DOC(),
    },
    temporal: {
      supportsStartFrame: false,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: false,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: MANUAL("Not a video model"),
    },
    camera: { controlLevel: "none", provenance: DOC() },
    motion: { controlLevel: "none", provenance: DOC() },
    output: {
      aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
      provenance: DOC(),
    },
    audio: emptyAudio(),
    execution: {
      mode: "sync",
      supportsPolling: false,
      supportsWebhooks: false,
      returnsTemporaryUrl: true,
      requiresDownloadBeforePersistence: true,
      provenance: ADAPTER(),
    },
    controls: { seed: false, provenance: ADAPTER() },
    limits: { maxReferenceCount: 1, supportedOutputFormats: ["image/jpeg", "image/png"] },
    economics: { known: false },
    metadata: {
      aliases: ["imagen-3", "imagen-4.0-generate-001", "gemini-2.0-flash-exp-image"],
      status: "active",
    },
  },
  {
    providerId: "gemini",
    modelId: "gemini-2.0-flash-tts",
    displayName: "Gemini 2.0 Flash TTS",
    modalities: ["audio", "text"],
    generationModes: ["text_to_speech"],
    adapterSupported: true,
    references: { supportedTypes: [], supportsMultipleReferences: false, provenance: DOC() },
    temporal: {
      supportsStartFrame: false,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: false,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: MANUAL(),
    },
    camera: { controlLevel: "none", provenance: DOC() },
    motion: { controlLevel: "none", provenance: DOC() },
    output: { provenance: DOC() },
    audio: { speech: true, nativeAudioGeneration: true, provenance: DOC("Gemini speech") },
    execution: { mode: "sync", supportsPolling: false, supportsWebhooks: false, returnsTemporaryUrl: true, requiresDownloadBeforePersistence: true, provenance: ADAPTER() },
    controls: { provenance: ADAPTER() },
    limits: { supportedOutputFormats: ["audio/mpeg", "audio/wav"] },
    economics: { known: false },
    metadata: { status: "active" },
  },

  // Higgsfield AI
  {
    providerId: "higgsfield",
    modelId: "seedance-2.5-i2v",
    displayName: "Higgsfield Seedance 2.5 I2V",
    modalities: ["video", "image"],
    generationModes: ["image_to_video"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image", "character", "environment", "location", "style"],
      maxReferences: 1,
      supportsMultipleReferences: false,
      supportsTypedReferences: false,
      provenance: MANUAL("Higgsfield Seedance I2V uses public HTTPS start image; end-frame optional"),
    },
    temporal: {
      supportsStartFrame: true,
      supportsEndFrame: true,
      supportsStartAndEndFrame: true,
      supportsTailFrame: true,
      supportsPreviousShotFrame: true,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: true,
      provenance: MANUAL("Higgsfield Seedance I2V supports first and end frame"),
    },
    camera: promptCamera(),
    motion: promptMotion(),
    output: {
      duration: {
        supportedValues: [...PROVIDER_VIDEO_CAPABILITIES.higgsfield.allowedDurationsSec],
        minSeconds: 4,
        maxSeconds: 30,
      },
      aspectRatios: ["16:9", "9:16", "1:1"],
      supportsNativeAudio: true,
      provenance: DOC("Higgsfield Seedance 2.5 supports native audio generation"),
    },
    audio: { nativeAudioGeneration: true, provenance: DOC("Native audio supported on Seedance 2.5") },
    execution: baseVideoExecution(true),
    controls: {
      seed: false,
      negativePrompt: false,
      provenance: ADAPTER("Controls limited to what videoI2vAdapter passes today"),
    },
    limits: {
      maxDurationSec: 30,
      maxReferenceCount: 1,
      supportedOutputFormats: ["video/mp4"],
    },
    economics: { known: false, notes: "No authoritative SPARK price table" },
    metadata: {
      aliases: ["seedance-2.5"],
      status: "active",
    },
  },
  {
    providerId: "higgsfield",
    modelId: "seedance-2.0-i2v",
    displayName: "Higgsfield Seedance 2.0 I2V",
    modalities: ["video", "image"],
    generationModes: ["image_to_video"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image", "character", "environment", "location", "style"],
      maxReferences: 1,
      supportsMultipleReferences: false,
      supportsTypedReferences: false,
      provenance: MANUAL("Higgsfield Seedance 2.0 start image + optional end frame"),
    },
    temporal: {
      supportsStartFrame: true,
      supportsEndFrame: true,
      supportsStartAndEndFrame: true,
      supportsTailFrame: true,
      supportsPreviousShotFrame: true,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: true,
      provenance: MANUAL(),
    },
    camera: promptCamera(),
    motion: promptMotion(),
    output: {
      duration: {
        supportedValues: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        minSeconds: 4,
        maxSeconds: 15,
      },
      aspectRatios: ["16:9", "9:16", "1:1"],
      supportsNativeAudio: true,
      provenance: DOC(),
    },
    audio: { nativeAudioGeneration: true, provenance: DOC() },
    execution: baseVideoExecution(true),
    controls: { seed: false, negativePrompt: false, provenance: ADAPTER() },
    limits: { maxDurationSec: 15, maxReferenceCount: 1, supportedOutputFormats: ["video/mp4"] },
    economics: { known: false },
    metadata: {
      aliases: ["seedance-2.0"],
      status: "active",
    },
  },
  {
    providerId: "higgsfield",
    modelId: "seedance-2.5-r2v",
    displayName: "Higgsfield Seedance 2.5 R2V",
    modalities: ["video", "image"],
    generationModes: ["image_to_video"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image", "character", "environment", "style"],
      maxReferences: 4,
      supportsMultipleReferences: true,
      supportsTypedReferences: false,
      provenance: MANUAL("Seedance 2.5 R2V reference slots"),
    },
    temporal: {
      supportsStartFrame: true,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: true,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: MANUAL(),
    },
    camera: promptCamera(),
    motion: promptMotion(),
    output: {
      duration: { supportedValues: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], minSeconds: 4, maxSeconds: 15 },
      aspectRatios: ["16:9", "9:16", "1:1"],
      supportsNativeAudio: true,
      provenance: DOC(),
    },
    audio: { nativeAudioGeneration: true, provenance: DOC() },
    execution: baseVideoExecution(true),
    controls: { seed: false, provenance: ADAPTER() },
    limits: { maxDurationSec: 15, maxReferenceCount: 4, supportedOutputFormats: ["video/mp4"] },
    economics: { known: false },
    metadata: {
      aliases: ["seedance-2.0-r2v"],
      status: "active",
    },
  },
  {
    providerId: "higgsfield",
    modelId: "soul-2",
    displayName: "Soul 2 Standard",
    modalities: ["image", "text"],
    generationModes: ["text_to_image"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image", "character", "style"],
      maxReferences: 4,
      supportsMultipleReferences: true,
      provenance: DOC("Soul 2 character / style reference"),
    },
    temporal: {
      supportsStartFrame: false,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: false,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: MANUAL("Not a video model"),
    },
    camera: { controlLevel: "none", provenance: DOC() },
    motion: { controlLevel: "none", provenance: DOC() },
    output: {
      aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
      resolutions: ["720p", "1080p"],
      provenance: DOC(),
    },
    audio: emptyAudio(),
    execution: {
      mode: "async",
      supportsPolling: true,
      supportsWebhooks: false,
      returnsTemporaryUrl: true,
      requiresDownloadBeforePersistence: true,
      provenance: ADAPTER(),
    },
    controls: { seed: true, provenance: ADAPTER() },
    limits: { maxReferenceCount: 4, supportedOutputFormats: ["image/jpeg", "image/png"] },
    economics: { known: false },
    metadata: {
      aliases: ["soul-standard", "higgsfield-ai/soul/v2/standard"],
      status: "active",
    },
  },
  {
    providerId: "higgsfield",
    modelId: "soul-cinema",
    displayName: "Soul Cinema",
    modalities: ["image", "text"],
    generationModes: ["text_to_image"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image", "style"],
      maxReferences: 2,
      supportsMultipleReferences: true,
      provenance: DOC(),
    },
    temporal: {
      supportsStartFrame: false,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: false,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: MANUAL(),
    },
    camera: { controlLevel: "none", provenance: DOC() },
    motion: { controlLevel: "none", provenance: DOC() },
    output: {
      aspectRatios: ["16:9", "9:16", "2.39:1"],
      resolutions: ["1080p"],
      provenance: DOC(),
    },
    audio: emptyAudio(),
    execution: {
      mode: "async",
      supportsPolling: true,
      supportsWebhooks: false,
      returnsTemporaryUrl: true,
      requiresDownloadBeforePersistence: true,
      provenance: ADAPTER(),
    },
    controls: { seed: true, provenance: ADAPTER() },
    limits: { maxReferenceCount: 2, supportedOutputFormats: ["image/jpeg", "image/png"] },
    economics: { known: false },
    metadata: {
      aliases: ["higgsfield-ai/soul/cinema"],
      status: "active",
    },
  },

  // Documented but NOT adapter-backed in SPARK execution registry — adapterSupported:false
  {
    providerId: "runway",
    modelId: "gen3",
    displayName: "Runway Gen-3",
    modalities: ["video"],
    generationModes: ["image_to_video", "text_to_video"],
    adapterSupported: false,
    references: {
      supportedTypes: ["image"],
      maxReferences: 1,
      supportsMultipleReferences: false,
      provenance: DOC(PROVIDER_VIDEO_CAPABILITIES.runway.notes),
    },
    temporal: {
      supportsStartFrame: true,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: false,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: DOC("Not exposed via SPARK adapter — effective capability disabled"),
    },
    camera: {
      controlLevel: "prompt_only",
      provenance: DOC("Marketing claims structured camera — SPARK adapter absent, so prompt_only"),
    },
    motion: promptMotion(),
    output: {
      duration: { supportedValues: [5, 10], minSeconds: 5, maxSeconds: 10 },
      aspectRatios: ["16:9", "9:16"],
      provenance: DOC(),
    },
    audio: emptyAudio(),
    execution: baseVideoExecution(false),
    controls: { provenance: DOC() },
    limits: { maxDurationSec: 10 },
    economics: { known: false },
    metadata: { deprecated: false, status: "disabled", notes: "Provider fact recorded; SPARK cannot execute yet" },
  },
  {
    providerId: "luma",
    modelId: "ray-2",
    displayName: "Luma Ray 2",
    modalities: ["video"],
    generationModes: ["image_to_video"],
    adapterSupported: false,
    references: {
      supportedTypes: ["image"],
      maxReferences: 2,
      supportsMultipleReferences: true,
      provenance: DOC(PROVIDER_VIDEO_CAPABILITIES.luma.notes),
    },
    temporal: {
      supportsStartFrame: true,
      supportsEndFrame: true,
      supportsStartAndEndFrame: true,
      supportsTailFrame: true,
      supportsPreviousShotFrame: false,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: DOC("Keyframe interpolation claimed in docs — adapter not registered"),
    },
    camera: promptCamera(),
    motion: promptMotion(),
    output: {
      duration: { supportedValues: [5, 9], minSeconds: 5, maxSeconds: 9 },
      aspectRatios: ["16:9", "9:16"],
      provenance: DOC(),
    },
    audio: emptyAudio(),
    execution: baseVideoExecution(false),
    controls: { provenance: DOC() },
    limits: { maxDurationSec: 9 },
    economics: { known: false },
    metadata: { status: "disabled", notes: "Provider fact recorded; SPARK cannot execute yet" },
  },

  // OpenAI
  {
    providerId: "openai",
    modelId: "gpt-image-1.5",
    displayName: "OpenAI Image 1.5",
    modalities: ["image", "text"],
    generationModes: ["text_to_image", "image_to_image"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image", "style"],
      maxReferences: 4,
      supportsMultipleReferences: true,
      provenance: DOC("Image generation / edit paths"),
    },
    temporal: {
      supportsStartFrame: false,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: false,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: MANUAL("Not a video model"),
    },
    camera: { controlLevel: "none", provenance: DOC() },
    motion: { controlLevel: "none", provenance: DOC() },
    output: {
      aspectRatios: ["1:1", "16:9", "9:16"],
      provenance: DOC(),
    },
    audio: emptyAudio(),
    execution: {
      mode: "sync",
      supportsPolling: false,
      supportsWebhooks: false,
      returnsTemporaryUrl: true,
      requiresDownloadBeforePersistence: true,
      provenance: ADAPTER(),
    },
    controls: { seed: false, provenance: ADAPTER() },
    limits: { maxReferenceCount: 4, supportedOutputFormats: ["image/png", "image/jpeg"] },
    economics: { known: false },
    metadata: {
      aliases: ["gpt-image", "gpt-image-1"],
      status: "active",
    },
  },
  {
    providerId: "openai",
    modelId: "dall-e-3",
    displayName: "DALL-E 3 (Legacy)",
    modalities: ["image", "text"],
    generationModes: ["text_to_image"],
    adapterSupported: true,
    references: {
      supportedTypes: ["image"],
      maxReferences: 1,
      supportsMultipleReferences: false,
      provenance: DOC(),
    },
    temporal: {
      supportsStartFrame: false,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: false,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: MANUAL("Not a video model"),
    },
    camera: { controlLevel: "none", provenance: DOC() },
    motion: { controlLevel: "none", provenance: DOC() },
    output: { aspectRatios: ["1:1", "16:9", "9:16"], provenance: DOC() },
    audio: emptyAudio(),
    execution: {
      mode: "sync",
      supportsPolling: false,
      supportsWebhooks: false,
      returnsTemporaryUrl: true,
      requiresDownloadBeforePersistence: true,
      provenance: ADAPTER(),
    },
    controls: { seed: false, provenance: ADAPTER() },
    limits: { maxReferenceCount: 1, supportedOutputFormats: ["image/png"] },
    economics: { known: false },
    metadata: { status: "deprecated" },
  },
  {
    providerId: "openai",
    modelId: "tts-1",
    displayName: "OpenAI TTS-1",
    modalities: ["audio", "text"],
    generationModes: ["text_to_speech"],
    adapterSupported: true,
    references: { supportedTypes: [], supportsMultipleReferences: false, provenance: DOC() },
    temporal: {
      supportsStartFrame: false,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: false,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: MANUAL(),
    },
    camera: { controlLevel: "none", provenance: DOC() },
    motion: { controlLevel: "none", provenance: DOC() },
    output: { provenance: DOC() },
    audio: { speech: true, nativeAudioGeneration: true, provenance: DOC("OpenAI TTS") },
    execution: {
      mode: "sync",
      supportsPolling: false,
      supportsWebhooks: false,
      returnsTemporaryUrl: true,
      requiresDownloadBeforePersistence: true,
      provenance: ADAPTER(),
    },
    controls: { provenance: ADAPTER() },
    limits: { supportedOutputFormats: ["audio/mpeg"] },
    economics: { known: false },
    metadata: {
      aliases: ["tts-1-hd", "gpt-4o-mini-tts"],
      status: "active",
    },
  },

  // ElevenLabs
  {
    providerId: "elevenlabs",
    modelId: "eleven_multilingual_v2",
    displayName: "ElevenLabs Multilingual v2",
    modalities: ["audio", "text"],
    generationModes: ["text_to_speech"],
    adapterSupported: true,
    references: {
      supportedTypes: [],
      supportsMultipleReferences: false,
      provenance: DOC(),
    },
    temporal: {
      supportsStartFrame: false,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: false,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: MANUAL(),
    },
    camera: { controlLevel: "none", provenance: DOC() },
    motion: { controlLevel: "none", provenance: DOC() },
    output: { provenance: DOC() },
    audio: {
      speech: true,
      nativeAudioGeneration: true,
      provenance: DOC("Voiceover narration"),
    },
    execution: {
      mode: "sync",
      supportsPolling: false,
      supportsWebhooks: false,
      returnsTemporaryUrl: true,
      requiresDownloadBeforePersistence: true,
      provenance: ADAPTER(),
    },
    controls: { provenance: ADAPTER() },
    limits: { supportedOutputFormats: ["audio/mpeg"] },
    economics: { known: false },
    metadata: {
      aliases: ["eleven-multilingual-v2", "eleven_monolingual_v1"],
      status: "active",
    },
  },
  {
    providerId: "elevenlabs",
    modelId: "eleven_turbo_v2_5",
    displayName: "ElevenLabs Turbo v2.5",
    modalities: ["audio", "text"],
    generationModes: ["text_to_speech"],
    adapterSupported: true,
    references: {
      supportedTypes: [],
      supportsMultipleReferences: false,
      provenance: DOC(),
    },
    temporal: {
      supportsStartFrame: false,
      supportsEndFrame: false,
      supportsStartAndEndFrame: false,
      supportsTailFrame: false,
      supportsPreviousShotFrame: false,
      supportsVideoContinuation: false,
      supportsVideoExtension: false,
      supportsPreviousVideoAsInput: false,
      supportsLastFrameContinuation: false,
      provenance: MANUAL(),
    },
    camera: { controlLevel: "none", provenance: DOC() },
    motion: { controlLevel: "none", provenance: DOC() },
    output: { provenance: DOC() },
    audio: {
      speech: true,
      nativeAudioGeneration: true,
      provenance: DOC("Fast narration"),
    },
    execution: {
      mode: "sync",
      supportsPolling: false,
      supportsWebhooks: false,
      returnsTemporaryUrl: true,
      requiresDownloadBeforePersistence: true,
      provenance: ADAPTER(),
    },
    controls: { provenance: ADAPTER() },
    limits: { supportedOutputFormats: ["audio/mpeg"] },
    economics: { known: false },
    metadata: {
      status: "active",
    },
  },
];

export function findProfiles(providerId?: string, modelId?: string): MediaCapabilityProfile[] {
  return MEDIA_CAPABILITY_PROFILES.filter((p) => {
    if (providerId && p.providerId.toLowerCase() !== providerId.toLowerCase()) return false;
    if (modelId) {
      const mLower = modelId.toLowerCase();
      if (p.modelId.toLowerCase() === mLower) return true;
      if (p.metadata?.aliases?.some((a) => a.toLowerCase() === mLower)) return true;
      return false;
    }
    return true;
  });
}
