export enum Capability {
  WEB_SEARCH = "WEB_SEARCH",
  LONG_CONTEXT = "LONG_CONTEXT",
  STRATEGIC_REASONING = "STRATEGIC_REASONING",
  WRITING = "WRITING",
  STYLE_CONSISTENCY = "STYLE_CONSISTENCY",
  TONE_ADAPTATION = "TONE_ADAPTATION",
  IMAGE_GENERATION = "IMAGE_GENERATION",
  VIDEO_GENERATION = "VIDEO_GENERATION",
  PUBLISHING = "PUBLISHING",
  ANALYTICS = "ANALYTICS",
  LEARNING = "LEARNING"
}
