export enum TaskState {
  PENDING = "PENDING",
  QUEUED = "QUEUED",
  RUNNING = "RUNNING",
  PAUSED = "PAUSED",
  WAITING_APPROVAL = "WAITING_APPROVAL",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  TIMED_OUT = "TIMED_OUT",
  RETRYING = "RETRYING"
}
