import { describe, it } from "node:test";
import assert from "node:assert/strict";
import type { NarrativeScript, ProductionBrief, ViralSpark, Production, ProductionRow, ViralSparkRow } from "../../../domain/types";
import { mergeProductionBrief, isFullNarrativeScript } from "./mergeProductionBrief";
import {
  domainViralSparkToInsert,
  viralSparkRowToDomain,
  domainProductionToInsert,
  productionRowToDomain,
} from "../../../backend/mappers/workspaceMappers";

const sampleNarrativeScript: NarrativeScript = {
  title: "The Roman Concrete Secret",
  logline: "Why ancient Roman piers outlasted modern concrete.",
  premise: "Volcanic ash and seawater trigger self-healing crystal growth.",
  targetDurationSec: 300,
  contentSource: "ai",
  hook: {
    spoken: "Ancient Roman concrete has survived underwater for over two thousand years.",
    visualIntent: "Slow underwater dive revealing colossal 2,000-year-old Roman seawall.",
  },
  chapters: [
    {
      title: "The Discovery",
      job: "hook",
      durationSec: 30,
      spoken: "In 2017, geologists extracted cores from ancient Roman piers submerged in the Mediterranean.",
      visualIntent: "Drilling rig pulling cylindrical rock core from turquoise waters.",
    },
    {
      title: "Chemical Analysis",
      job: "development",
      durationSec: 45,
      spoken: "Under electron microscopes, they found aluminous tobermorite crystals growing through micro-cracks.",
      visualIntent: "SEM magnification revealing needle-like interlocking crystals.",
    },
  ],
  cta: {
    spoken: "Follow for deep-dive engineering histories.",
    onScreen: "FOLLOW FOR ARCHITECTURAL MYSTERIES",
  },
  fullSpokenScript:
    "Ancient Roman concrete has survived underwater for over two thousand years. " +
    "In 2017, geologists extracted cores from ancient Roman piers submerged in the Mediterranean. " +
    "Under electron microscopes, they found aluminous tobermorite crystals growing through micro-cracks. " +
    "Follow for deep-dive engineering histories.",
};

describe("SPARK Script Persistence & Canonical Brief Protection", () => {
  it("Fixture 1: mergeProductionBrief keeps prev.narrativeScript when next only updates generationProgress", () => {
    const prevBrief: ProductionBrief = {
      title: "Roman Concrete",
      productionMode: "deep",
      targetDurationSec: 300,
      hook: "Ancient Roman concrete has survived underwater.",
      scriptOutline: "Outline",
      beats: [
        {
          timecode: "[00:00-00:30]",
          valueJob: "hook",
          spokenLines: "In 2017 geologists extracted cores.",
          durationSec: 30,
        },
      ],
      spokenCta: "Follow for more",
      onScreenCta: "FOLLOW",
      visualDirection: "Cinematic underwater",
      caption: "Roman concrete",
      platformRecommendation: "YouTube Long-form",
      whyThisWorks: "Ancient mysteries",
      contentSource: "ai",
      brandFitScore: 95,
      narrativeScript: sampleNarrativeScript,
    };

    const nextProgressPatch: Partial<ProductionBrief> = {
      generationProgress: {
        percent: 45,
        stage: "Synthesizing Clips",
        message: "Rendering chapter 2 keyframe",
        stages: [],
        updatedAt: new Date().toISOString(),
      },
      videoUrl: "https://storage.spark.app/videos/clip1.mp4",
    };

    const merged = mergeProductionBrief(prevBrief, nextProgressPatch);
    assert.ok(merged, "Merged brief must exist");
    assert.ok(merged.narrativeScript, "narrativeScript MUST NOT be wiped by progress patch");
    assert.equal(merged.narrativeScript.title, "The Roman Concrete Secret");
    assert.equal(merged.narrativeScript.chapters.length, 2);
    assert.equal(merged.generationProgress?.percent, 45);
    assert.equal(merged.videoUrl, "https://storage.spark.app/videos/clip1.mp4");
    assert.equal(merged.beats.length, 1, "Beats preserved from prevBrief");
  });

  it("Fixture 2: mergeProductionBrief overlays narrativeScript when next contains a full valid script", () => {
    const prevBrief: Partial<ProductionBrief> = {
      title: "Old Script",
      narrativeScript: {
        ...sampleNarrativeScript,
        title: "Old Script Title",
      },
    };

    const nextFullScript: NarrativeScript = {
      ...sampleNarrativeScript,
      title: "New Re-generated Title",
      fullSpokenScript: "A completely new script generated by writer.",
    };

    const merged = mergeProductionBrief(prevBrief, { narrativeScript: nextFullScript });
    assert.equal(merged?.narrativeScript?.title, "New Re-generated Title");
    assert.equal(merged?.narrativeScript?.fullSpokenScript, "A completely new script generated by writer.");
  });

  it("Fixture 3: mergeProductionBrief keeps prev.beats and prev.storyboard if next has empty arrays", () => {
    const prevBrief: Partial<ProductionBrief> = {
      beats: [{ timecode: "[00:00-00:30]", valueJob: "hook", spokenLines: "Intro", durationSec: 30 }],
      storyboard: [{ scene: 1, duration: "30s", durationSec: 30, shotList: "Shot 1" }],
    };

    const merged = mergeProductionBrief(prevBrief, { beats: [], storyboard: [] });
    assert.equal(merged?.beats.length, 1, "prev.beats must be preserved when next is empty");
    assert.equal(merged?.storyboard?.length, 1, "prev.storyboard must be preserved when next is empty");
  });

  it("Fixture 4: domainViralSparkToInsert writes narrativeScript into evidence and preserves existing keys", () => {
    const spark: ViralSpark = {
      id: "11111111-1111-4111-8111-111111111111",
      title: "The Roman Concrete Secret",
      platformFit: "YouTube Long-form",
      hook: "Ancient Roman concrete has survived underwater.",
      views: "1.2M",
      velocity: "High",
      brandFitScore: 92,
      category: "rising",
      timeWindow: "Open",
      productionTime: "12h",
      whyNow: "New study published",
      angle: "Engineering miracle",
      audienceEmotion: "Awe",
      expectedRetention: "75%",
      difficulty: "Medium",
      riskLevel: "Low",
      suggestedFormat: "Long-form",
      suggestedProductionMode: "deep",
      status: "ready",
      narrativeScriptObj: sampleNarrativeScript,
      targetDurationSec: 300,
    };

    const existingEvidence = {
      existingKey: "custom_data",
      sourceUrls: ["https://example.com/roman-concrete"],
    };

    const row = domainViralSparkToInsert("brand-1", spark, existingEvidence);
    const ev = row.evidence as any;

    assert.ok(ev, "evidence must be present");
    assert.equal(ev.existingKey, "custom_data", "Must preserve existing evidence keys");
    assert.deepEqual(ev.sourceUrls, ["https://example.com/roman-concrete"], "Must preserve sourceUrls");
    assert.ok(ev.narrativeScript, "Must write narrativeScript into evidence");
    assert.equal(ev.narrativeScript.title, "The Roman Concrete Secret");
    assert.equal(ev.suggestedScript, sampleNarrativeScript.fullSpokenScript);
    assert.equal(ev.spoken_beats.length, 2);
    assert.equal(ev.opening_line, sampleNarrativeScript.hook.spoken);
    assert.equal(ev.targetDurationSec, 300);
    assert.equal(row.status, "ready");
  });

  it("Fixture 5: viralSparkRowToDomain hydrates script fields from evidence", () => {
    const row: ViralSparkRow = {
      id: "11111111-1111-4111-8111-111111111111",
      brand_id: "brand-1",
      title: "The Roman Concrete Secret",
      opportunity: "Roman concrete",
      why_now: "Recent excavation",
      audience_fit: "YouTube",
      brand_fit: "92",
      hook_potential: "High",
      confidence: "92",
      risk: "Low",
      expected_outcome: "1M",
      status: "ready",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      evidence: {
        narrativeScript: sampleNarrativeScript,
        suggestedScript: sampleNarrativeScript.fullSpokenScript,
        spoken_beats: ["Beat 1", "Beat 2"],
        opening_line: "Opening line hook",
        targetDurationSec: 300,
        status: "ready",
      },
    };

    const domainSpark = viralSparkRowToDomain(row);
    assert.ok(domainSpark.narrativeScriptObj, "narrativeScriptObj must be hydrated");
    assert.equal(domainSpark.narrativeScriptObj.title, "The Roman Concrete Secret");
    assert.equal(domainSpark.suggestedScript, sampleNarrativeScript.fullSpokenScript);
    assert.deepEqual(domainSpark.spoken_beats, ["Beat 1", "Beat 2"]);
    assert.equal(domainSpark.opening_line, "Opening line hook");
    assert.equal(domainSpark.targetDurationSec, 300);
    assert.equal(domainSpark.status, "ready");
  });

  it("Fixture 6: domainProductionToInsert and productionRowToDomain round-trip brief.narrativeScript", () => {
    const brief: ProductionBrief = {
      title: "The Roman Concrete Secret",
      productionMode: "deep",
      targetDurationSec: 300,
      hook: "Ancient Roman concrete",
      scriptOutline: "Outline",
      beats: [],
      spokenCta: "CTA",
      onScreenCta: "CTA",
      visualDirection: "Visuals",
      caption: "Caption",
      platformRecommendation: "YouTube",
      whyThisWorks: "Why",
      contentSource: "ai",
      brandFitScore: 90,
      narrativeScript: sampleNarrativeScript,
    };

    const prod: Production = {
      id: "22222222-2222-4222-8222-222222222222",
      title: "The Roman Concrete Secret",
      status: "Drafting",
      mode: "deep",
      dateCreated: "2026-09-17",
      aspectRatio: "16:9",
      formats: ["YouTube Long-form"],
      scenes: [],
      brief,
    };

    const row = domainProductionToInsert("brand-1", prod) as ProductionRow;
    assert.ok(row.brief, "row.brief must exist");

    const hydrated = productionRowToDomain(row);
    assert.ok(hydrated.brief, "hydrated.brief must exist");
    assert.ok(hydrated.brief.narrativeScript, "brief.narrativeScript MUST survive round-trip");
    assert.equal(hydrated.brief.narrativeScript.title, "The Roman Concrete Secret");
    assert.equal(hydrated.brief.narrativeScript.chapters.length, 2);
    assert.equal(
      hydrated.brief.narrativeScript.fullSpokenScript,
      sampleNarrativeScript.fullSpokenScript
    );
  });

  it("Fixture 7: Simulates logout/login (serialize to DB row, reload) — keeps brief.narrativeScript.fullSpokenScript", () => {
    // 1. In-memory production with movie script
    const brief: ProductionBrief = {
      title: "Long-form Documentary",
      productionMode: "deep",
      targetDurationSec: 300,
      hook: "Did Romans invent self-healing concrete?",
      scriptOutline: "Full Outline",
      beats: [],
      spokenCta: "Subscribe",
      onScreenCta: "SUBSCRIBE",
      visualDirection: "Hyper-detailed",
      caption: "Documentary",
      platformRecommendation: "YouTube Long-form",
      whyThisWorks: "Proven virality",
      contentSource: "ai",
      brandFitScore: 94,
      narrativeScript: sampleNarrativeScript,
    };

    const initialProd: Production = {
      id: "33333333-3333-4333-8333-333333333333",
      title: "Long-form Documentary",
      status: "Ready for Review",
      mode: "deep",
      dateCreated: "2026-09-17",
      aspectRatio: "16:9",
      formats: ["YouTube Long-form"],
      scenes: [],
      brief,
    };

    // 2. Insert into cloud (serialize to DB row)
    const dbRow = domainProductionToInsert("brand-1", initialProd) as ProductionRow;

    // 3. User logs out and logs back in (read from cloud row)
    const reloaded = productionRowToDomain(dbRow);

    // 4. Verify fullSpokenScript is present and intact
    assert.ok(reloaded.brief?.narrativeScript, "Reloaded brief must have narrativeScript");
    assert.equal(
      reloaded.brief?.narrativeScript?.fullSpokenScript,
      sampleNarrativeScript.fullSpokenScript,
      "fullSpokenScript must be preserved verbatim across logout/login"
    );
  });

  it("Fixture 8: Evaluated draft script with evaluation.ok = false persists draft status + lastError", () => {
    const failedScript: NarrativeScript = {
      ...sampleNarrativeScript,
      title: "Failed Script",
    };

    const spark: ViralSpark = {
      id: "44444444-4444-4444-8444-444444444444",
      title: "Failed Script",
      platformFit: "YouTube",
      hook: "Hook",
      views: "—",
      velocity: "—",
      brandFitScore: 60,
      category: "rising",
      timeWindow: "Open",
      productionTime: "6h",
      whyNow: "Why",
      angle: "Angle",
      audienceEmotion: "Curiosity",
      expectedRetention: "50%",
      difficulty: "Medium",
      riskLevel: "Medium",
      suggestedFormat: "Short",
      suggestedProductionMode: "standard",
      status: "draft",
      lastError: "Script chapters sum to 75s, which deviates by more than 15% from target duration 300s.",
      narrativeScriptObj: failedScript,
      targetDurationSec: 300,
    };

    const row = domainViralSparkToInsert("brand-1", spark);
    assert.equal(row.status, "draft", "Status must remain draft");
    const ev = row.evidence as any;
    assert.equal(ev.status, "draft");
    assert.match(ev.lastError, /deviates by more than 15%/);
    assert.ok(ev.narrativeScript, "Writer's script must NOT be dropped on evaluation failure");

    const reloadedSpark = viralSparkRowToDomain(row as ViralSparkRow);
    assert.equal(reloadedSpark.status, "draft");
    assert.equal(reloadedSpark.lastError, spark.lastError);
    assert.ok(reloadedSpark.narrativeScriptObj);
  });
});
