/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState, useEffect } from 'react';
import { Tab, Brand, Account, Spark, Production, ReviewItem, PublishJob, Insight, Memory, Asset } from './types';
import {
  mockBrands,
  mockAccounts,
  mockSparks,
  mockProductions,
  mockReviewItems,
  mockPublishJobs,
  mockInsights,
  mockMemories,
  mockAssets,
  mockAudios
} from './mockData';

// Subcomponents
import Header from './components/Header';
import Sidebar from './components/Sidebar';
import BottomNav from './components/BottomNav';
import Dashboard from './components/Dashboard';
import MySpark from './components/MySpark';
import ViralSparks from './components/ViralSparks';
import Review from './components/Review';
import CalendarView from './components/CalendarView';
import Analytics from './components/Analytics';
import More from './components/More';

export default function App() {
  // Global active states
  const [currentTab, setCurrentTab] = useState<Tab>('spark');
  const [selectedBrand, setSelectedBrand] = useState<Brand>(mockBrands[0]);

  // Brand-dependent collections
  const [brands, setBrands] = useState<Brand[]>(mockBrands);
  const [accounts, setAccounts] = useState<Account[]>(mockAccounts[mockBrands[0].id]);
  const [sparks, setSparks] = useState<Spark[]>(mockSparks[mockBrands[0].id]);
  const [productions, setProductions] = useState<Production[]>(mockProductions[mockBrands[0].id]);
  const [reviewItems, setReviewItems] = useState<ReviewItem[]>(mockReviewItems[mockBrands[0].id]);
  const [publishJobs, setPublishJobs] = useState<PublishJob[]>(mockPublishJobs[mockBrands[0].id]);
  const [insights, setInsights] = useState<Insight[]>(mockInsights[mockBrands[0].id]);
  const [memories, setMemories] = useState<Memory[]>(mockMemories[mockBrands[0].id]);
  const [assets, setAssets] = useState<Asset[]>(mockAssets[mockBrands[0].id]);

  // Sync state whenever selected brand changes
  useEffect(() => {
    const brandId = selectedBrand.id;
    setAccounts(mockAccounts[brandId] || []);
    setSparks(mockSparks[brandId] || []);
    setProductions(mockProductions[brandId] || []);
    setReviewItems(mockReviewItems[brandId] || []);
    setPublishJobs(mockPublishJobs[brandId] || []);
    setInsights(mockInsights[brandId] || []);
    setMemories(mockMemories[brandId] || []);
    setAssets(mockAssets[brandId] || []);
  }, [selectedBrand]);

  // Simulate production pipeline incremental progress rendering
  useEffect(() => {
    if (productions.length === 0) return;

    const interval = setInterval(() => {
      setProductions((prev) =>
        prev.map((prod) => {
          if (prod.progress >= 100) {
            // Production completed rendering!
            // Automatically push a simulated Review Item to the queue if not already done
            const reviewExists = reviewItems.some((item) => item.sparkId === prod.sparkId);
            if (!reviewExists) {
              const newReview: ReviewItem = {
                id: `rev-${Date.now()}`,
                sparkId: prod.sparkId,
                title: prod.title,
                hook: `SPARK Autogenerated hook from ${prod.title}`,
                description: `Autonomous content draft generated by SPARK. Pair subtitles with character pacing rules to publish. #sparkmedia #automation #growth`,
                tags: ['sparkmedia', 'automation', 'growth'],
                videoPreviewUrl: 'https://assets.mixkit.co/videos/preview/mixkit-matrix-style-computer-code-running-9114-large.mp4',
                audioId: 'aud-1',
                qualityChecks: [
                  { id: 'qc-sim-1', label: 'Audio Normalization Approved', passed: true },
                  { id: 'qc-sim-2', label: 'Aspect Ratio Verification (9:16 Portrait)', passed: true },
                  { id: 'qc-sim-3', label: 'Monospace visual text overlay sync', passed: true }
                ],
                exportPackage: {
                  mp4Url: '#',
                  metadata: {
                    title: prod.title,
                    description: `Autonomous content draft generated by SPARK.`,
                    tags: ['sparkmedia', 'automation']
                  }
                },
                status: 'pending'
              };
              setReviewItems((prevReviews) => [newReview, ...prevReviews]);
            }
            return { ...prod, progress: 100, step: 'rendered' };
          }

          // Advance progression
          const nextProgress = prod.progress + Math.floor(Math.random() * 15) + 5;
          const stepsOrder: Production['step'][] = ['research', 'scripting', 'storyboarding', 'voiceover', 'visual_assembly', 'rendered'];
          const currentIdx = stepsOrder.indexOf(prod.step);
          const nextStep = currentIdx < stepsOrder.length - 2 ? stepsOrder[currentIdx + 1] : prod.step;

          return {
            ...prod,
            progress: Math.min(nextProgress, 100),
            step: nextProgress >= 100 ? 'rendered' : nextStep
          };
        }).filter((prod) => prod.progress < 100) // remove completed items from active list after they trigger review
      );
    }, 4000);

    return () => clearInterval(interval);
  }, [productions, reviewItems]);

  // 1. Toggles for operational modes
  const handleUpdateModes = (productionMode: Brand['productionMode'], automationMode: Brand['automationMode']) => {
    const updatedBrand = { ...selectedBrand, productionMode, automationMode };
    setSelectedBrand(updatedBrand);
    setBrands((prev) => prev.map((b) => (b.id === selectedBrand.id ? updatedBrand : b)));
  };

  // 2. Persona Updates
  const handleUpdateCharacter = (character: Brand['character']) => {
    const updatedBrand = { ...selectedBrand, character };
    setSelectedBrand(updatedBrand);
    setBrands((prev) => prev.map((b) => (b.id === selectedBrand.id ? updatedBrand : b)));
  };

  // 3. Brain Memory management
  const handleAddMemory = (topic: string, fact: string) => {
    const newMemory: Memory = {
      id: `mem-${Date.now()}`,
      topic,
      learnedFact: fact,
      provenHypothesis: true,
      updatedAt: new Date().toISOString()
    };
    setMemories((prev) => [newMemory, ...prev]);
  };

  const handleDeleteMemory = (id: string) => {
    setMemories((prev) => prev.filter((m) => m.id !== id));
  };

  // 4. Dispatch a Spark to active rendering pipeline
  const handleInitiateProduction = (spark: Spark) => {
    // Mark spark status as producing
    setSparks((prev) =>
      prev.map((s) => (s.id === spark.id ? { ...s, status: 'producing' } : s))
    );

    const newProd: Production = {
      id: `prod-${Date.now()}`,
      sparkId: spark.id,
      title: spark.title,
      step: 'research',
      progress: 10,
      startedAt: new Date().toISOString(),
      estimatedCompletion: new Date(Date.now() + 5 * 60 * 1000).toISOString() // 5 mins from now
    };

    setProductions((prev) => [newProd, ...prev]);
  };

  // 5. Approve a reviewed draft and queue it for distribution
  const handleApproveItem = (reviewItemId: string, publishTime: string) => {
    // Set status to approved
    setReviewItems((prev) =>
      prev.map((item) => (item.id === reviewItemId ? { ...item, status: 'approved' } : item))
    );

    // Spawn publishing job
    const newJob: PublishJob = {
      id: `pub-${Date.now()}`,
      reviewItemId,
      platform: accounts[0]?.platform || 'tiktok',
      status: 'scheduled',
      publishTime
    };

    setPublishJobs((prev) => [newJob, ...prev]);
  };

  const handleRejectItem = (reviewItemId: string) => {
    setReviewItems((prev) =>
      prev.map((item) => (item.id === reviewItemId ? { ...item, status: 'rejected' } : item))
    );
  };

  // 6. Connect/disconnect custom channels
  const handleConnectAccount = (platform: Account['platform'], username: string) => {
    const newAccount: Account = {
      id: `acc-${Date.now()}`,
      platform,
      username,
      connected: true,
      followersCount: Math.floor(Math.random() * 5000) + 100
    };
    setAccounts((prev) => [...prev, newAccount]);
  };

  const handleDisconnectAccount = (id: string) => {
    setAccounts((prev) => prev.filter((acc) => acc.id !== id));
  };

  // 7. Instant simulated release cycle (scheduled -> published)
  const handlePublishNow = (jobId: string) => {
    setPublishJobs((prev) =>
      prev.map((job) => {
        if (job.id === jobId) {
          return {
            ...job,
            status: 'published',
            publishTime: new Date().toISOString(),
            engagementStats: {
              views: Math.floor(Math.random() * 80000) + 15000,
              likes: Math.floor(Math.random() * 6000) + 1200,
              comments: Math.floor(Math.random() * 400) + 40,
              shares: Math.floor(Math.random() * 1500) + 100
            }
          };
        }
        return job;
      })
    );

    // Create a synthesized learning insight triggered by this publish!
    const newInsight: Insight = {
      id: `ins-${Date.now()}`,
      category: 'hook',
      headline: 'Instant publish trigger proved high mid-day retention',
      metricChange: '+18% Views',
      description: 'SPARK parsed the audience distribution graph and verified this release caught a critical midday browsing spike.',
      timestamp: new Date().toISOString()
    };
    setInsights((prev) => [newInsight, ...prev]);
  };

  // 8. Trigger Autonomous discovery simulation from dashboard button
  const handleTriggerAutonomousProduction = () => {
    // Generate simulated spark
    const newSpark: Spark = {
      id: `spark-sim-${Date.now()}`,
      title: 'ChatGPT Reasoning secret prompts for B2B leverage',
      hook: 'Most SaaS builders are prompting ChatGPT like high school students. Avoid these 3 words instead.',
      viralScore: 92,
      sourceTrend: 'Autonomous Twitter scan on OpenAI o3 developers',
      discoveredAt: new Date().toISOString(),
      status: 'producing'
    };
    setSparks((prev) => [newSpark, ...prev]);

    // Put directly in Review stage
    const newReview: ReviewItem = {
      id: `rev-sim-${Date.now()}`,
      sparkId: newSpark.id,
      title: newSpark.title,
      hook: newSpark.hook,
      description: 'Autonomous content draft generated by SPARK.',
      tags: ['openai', 'chatgpt', 'saashacks'],
      videoPreviewUrl: 'https://assets.mixkit.co/videos/preview/mixkit-matrix-style-computer-code-running-9114-large.mp4',
      audioId: 'aud-1',
      qualityChecks: [
        { id: 'qc-a-1', label: 'Audio Normalization (Target -14 LUFS)', passed: true },
        { id: 'qc-a-2', label: 'Aspect Ratio Verification (9:16 Portrait)', passed: true },
        { id: 'qc-a-3', label: 'High-Retention Hook Pacing Checked', passed: true }
      ],
      exportPackage: {
        mp4Url: '#',
        metadata: {
          title: newSpark.title,
          description: 'Avoid legacy descriptions. Use this direct prompt tutorial instead.',
          tags: ['openai', 'developer', 'saashacks']
        }
      },
      status: 'pending'
    };
    setReviewItems((prev) => [newReview, ...prev]);
  };

  const pendingReviewCount = reviewItems.filter((item) => item.status === 'pending').length;

  return (
    <div className="flex min-h-screen flex-col bg-zinc-950 text-zinc-100" id="spark-media-os-app">
      {/* Upper header - context switches & channel indicators */}
      <Header
        brands={brands}
        selectedBrand={selectedBrand}
        onSelectBrand={setSelectedBrand}
        onNavigateToTab={setCurrentTab}
        connectedAccounts={accounts}
        currentTab={currentTab}
      />

      {/* Main split dashboard content */}
      <div className="flex flex-1">
        {/* Left side nav panel (Desktop Only) */}
        <Sidebar
          currentTab={currentTab}
          onSelectTab={setCurrentTab}
          pendingReviewCount={pendingReviewCount}
        />

        {/* Central screen deck (Fluid and responsive) */}
        <main className="flex-1 overflow-y-auto bg-zinc-950" id="main-content-scroll">
          {currentTab === 'spark' && (
            <Dashboard
              brand={selectedBrand}
              productions={productions}
              pendingReviewCount={pendingReviewCount}
              onUpdateModes={handleUpdateModes}
              onNavigateToTab={setCurrentTab}
              onTriggerAutonomousProduction={handleTriggerAutonomousProduction}
            />
          )}

          {currentTab === 'my-spark' && (
            <MySpark
              brand={selectedBrand}
              memories={memories}
              onUpdateCharacter={handleUpdateCharacter}
              onAddMemory={handleAddMemory}
              onDeleteMemory={handleDeleteMemory}
            />
          )}

          {currentTab === 'viral-sparks' && (
            <ViralSparks
              sparks={sparks}
              audios={mockAudios}
              onInitiateProduction={handleInitiateProduction}
              onNavigateToTab={setCurrentTab}
            />
          )}

          {currentTab === 'review' && (
            <Review
              reviewItems={reviewItems}
              audios={mockAudios}
              onApproveItem={handleApproveItem}
              onRejectItem={handleRejectItem}
              onNavigateToTab={setCurrentTab}
            />
          )}

          {currentTab === 'calendar' && (
            <CalendarView
              publishJobs={publishJobs}
              reviewItems={reviewItems}
              onPublishNow={handlePublishNow}
            />
          )}

          {currentTab === 'analytics' && (
            <Analytics
              insights={insights}
              memories={memories}
            />
          )}

          {currentTab === 'more' && (
            <More
              connectedAccounts={accounts}
              assets={assets}
              onConnectAccount={handleConnectAccount}
              onDisconnectAccount={handleDisconnectAccount}
              onNavigateToTab={setCurrentTab}
            />
          )}
        </main>
      </div>

      {/* Touch-optimized responsive mobile navigation bottom bar (Mobile Only) */}
      <BottomNav
        currentTab={currentTab}
        onSelectTab={setCurrentTab}
        pendingReviewCount={pendingReviewCount}
      />
    </div>
  );
}
